// <auto-generated />
using ChampsSpeciaux.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChampsSpeciaux.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220616013855_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChampsSpeciaux.Models.Travel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TravelImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Travel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "<span class='ILfuVd'>Le <b>ski</b> de pente raide, ou <b>ski extrême</b>, est une discipline du <b>ski</b> qui conjugue alpinisme et <b>ski</b>de montagne et se pratique dans un couloir ou sur une pente généralement au départ d'un sommet que l'''on atteint après une ascension à pied et / ou à < b > ski </ b > en mettant parfois en œuvre du matériel d'''alpinisme (piolets, crampons).</span>",
                            Name = "Ski Extrême",
                            TravelImage = "9f8d9bc0-f597-483f-84af-4665d4df15a3.png"
                        },
                        new
                        {
                            Id = 2,
                            Description = "<p>La <font color='#9c00ff'><b>montgolfière</b></font> a toujours marqué l''’imaginaire. Capable de revêtir n''’importe quelle couleur, elle inspire par sa beauté et sa grandeur. <u>Synonyme</u> d’''aventure, elle a aussi fait l'’'objet de nombreux récits, qui racontent les péripéties de voyages intrépides vers l’inconnu. Riche en histoire, les origines de cette invention nous viennent d'’'une époque lointaine. Aujourd’hui, elle continue d’émerveiller par sa capacité à s’élever, pratiquement comme par magie<br></p>",
                            Name = "Montgolfière",
                            TravelImage = "b7c32080-b025-47bb-a05c-858857795fb9.png"
                        },
                        new
                        {
                            Id = 3,
                            Description = "<p><b>Kalymnos</b> est une île grecque montagneuse de l’archipel du <font color='#000000' style='background - color: rgb(255, 255, 0); '>Dodécanèse</font> dans la mer Égée. Elle attire à chaque année de nombreux grimpeurs venus surmonter ses falaises de calcaire. Ces dernières offrent tous les styles d''’escalade qui conviendront aux grimpeurs de tous les niveaux.<br></p>",
                            Name = "escalade",
                            TravelImage = "4035923b-acbe-4ca5-a199-a2eb978325fe.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
