// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieLand_DataAccess.Data;

namespace MovieLand_DataAccess.Migrations
{
    [DbContext(typeof(MovieLandDbContext))]
    [Migration("20220607123021_S06A_MovieLand_Seed")]
    partial class S06A_MovieLand_Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MovieLand_Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Poster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<int>("Runtime")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Poster = "SY23IX2QWdXCiX2YkIerTweUcd.jpg",
                            ReleaseYear = 1993,
                            Runtime = 141,
                            Title = "L'affaire Pélican"
                        },
                        new
                        {
                            MovieId = 2,
                            Poster = "pNz1NREgddPdlzytlR8mW4B26fW.jpg",
                            ReleaseYear = 2002,
                            Runtime = 121,
                            Title = "Spider-Man"
                        },
                        new
                        {
                            MovieId = 3,
                            Poster = "32bzh3HnRZdE8oM9pwfmGJUYnvl.jpg",
                            ReleaseYear = 2002,
                            Runtime = 89,
                            Title = "Scooby-Doo"
                        },
                        new
                        {
                            MovieId = 4,
                            Poster = "e2oWzbhxfqAlJ83ea38D64VD1RR.jpg",
                            ReleaseYear = 2005,
                            Runtime = 128,
                            Title = "L'interprète"
                        },
                        new
                        {
                            MovieId = 5,
                            Poster = "wzIO3ytxeSNt1wRpXLIdkNbGoDm.jpg",
                            ReleaseYear = 2005,
                            Runtime = 120,
                            Title = "M. et Mme Smith"
                        },
                        new
                        {
                            MovieId = 6,
                            Poster = "hjWcpt9GI9v9NSkex58GUZhlS25.jpg",
                            ReleaseYear = 2005,
                            Runtime = 129,
                            Title = "The Legend of Zorro"
                        },
                        new
                        {
                            MovieId = 7,
                            Poster = "q6wt3HwGwRnzKbpgwNTeIZgHKkH.jpg",
                            ReleaseYear = 2006,
                            Runtime = 149,
                            Title = "Le code Da Vinci"
                        },
                        new
                        {
                            MovieId = 8,
                            Poster = "x7zBSbzWyJB1VB10BAMMWTOWe45.jpg",
                            ReleaseYear = 2007,
                            Runtime = 93,
                            Title = "Prémonition"
                        },
                        new
                        {
                            MovieId = 9,
                            Poster = "svCEllDaXbt3eNlbf4HZLA5kKjJ.jpg",
                            ReleaseYear = 2007,
                            Runtime = 113,
                            Title = "Fracture"
                        },
                        new
                        {
                            MovieId = 10,
                            Poster = "4SBTOPWMM3My5nDIlpNHt6dg78d.jpg",
                            ReleaseYear = 2007,
                            Runtime = 139,
                            Title = "Spider-Man 3"
                        },
                        new
                        {
                            MovieId = 11,
                            Poster = "7zEWoMDAgvgHlv1D11vF3Br3ZTd.jpg",
                            ReleaseYear = 2008,
                            Runtime = 113,
                            Title = "L'Incroyable Hulk"
                        },
                        new
                        {
                            MovieId = 12,
                            Poster = "lLbElXAzCNxaCaHGBDvLv7KM9QM.jpg",
                            ReleaseYear = 2008,
                            Runtime = 118,
                            Title = "L'Oeil du mal"
                        },
                        new
                        {
                            MovieId = 13,
                            Poster = "uvd0fOK5dZsZDMICflMxotedsmC.jpg",
                            ReleaseYear = 2009,
                            Runtime = 121,
                            Title = "Prédictions"
                        },
                        new
                        {
                            MovieId = 14,
                            Poster = "cAFfhia4joDvGK2zvL6lOue6Xlx.jpg",
                            ReleaseYear = 2009,
                            Runtime = 127,
                            Title = "State of Play"
                        },
                        new
                        {
                            MovieId = 15,
                            Poster = "zS0B5iu68dyBNXUoSpZmIaxh2ua.jpg",
                            ReleaseYear = 2009,
                            Runtime = 138,
                            Title = "Anges & Démons"
                        },
                        new
                        {
                            MovieId = 16,
                            Poster = "OuABrWGUHbIAmaE0wkmNMvy1A7.jpg",
                            ReleaseYear = 2011,
                            Runtime = 113,
                            Title = "Hors de moi"
                        },
                        new
                        {
                            MovieId = 17,
                            Poster = "786fsgu3U7P9icbllwpd6yfOIiD.jpg",
                            ReleaseYear = 2011,
                            Runtime = 105,
                            Title = "Sans limites"
                        },
                        new
                        {
                            MovieId = 18,
                            Poster = "7MMrRbyOts9v1YHYoc7LSrz8XnQ.jpg",
                            ReleaseYear = 2011,
                            Runtime = 123,
                            Title = "Green Lantern"
                        },
                        new
                        {
                            MovieId = 19,
                            Poster = "bRMdfPlHNbnpifEUIOEajxl8BcX.jpg",
                            ReleaseYear = 2011,
                            Runtime = 101,
                            Title = "Johnny English renaît"
                        },
                        new
                        {
                            MovieId = 20,
                            Poster = "kbeSPWIRkWZYQgLCyPqxjj4G0kx.jpg",
                            ReleaseYear = 2011,
                            Runtime = 129,
                            Title = "Sherlock Holmes: Le jeu des ombres"
                        },
                        new
                        {
                            MovieId = 21,
                            Poster = "i0jXQFuSsKLDNxWH7mV0BijugtY.jpg",
                            ReleaseYear = 2011,
                            Runtime = 95,
                            Title = "Ghost Rider: Esprit de vengeance"
                        },
                        new
                        {
                            MovieId = 22,
                            Poster = "gsIkMf1VErbF0xtrgXEZXqLgsBG.jpg",
                            ReleaseYear = 2012,
                            Runtime = 137,
                            Title = "L'extraordinaire Spider-Man"
                        },
                        new
                        {
                            MovieId = 23,
                            Poster = "sqKvTMHHbkH5ak4jPIPHCTQqb6W.jpg",
                            ReleaseYear = 2012,
                            Runtime = 121,
                            Title = "Total Recall: Mémoires programmées"
                        },
                        new
                        {
                            MovieId = 24,
                            Poster = "hagmYjjQBR5I73YFsYMXMY2Uoj3.jpg",
                            ReleaseYear = 2013,
                            Runtime = 109,
                            Title = "Emprise sur la ville"
                        },
                        new
                        {
                            MovieId = 25,
                            Poster = "n3pCxunmHrK6AWpLaAThgYiguWK.jpg",
                            ReleaseYear = 2013,
                            Runtime = 118,
                            Title = "Parker"
                        },
                        new
                        {
                            MovieId = 26,
                            Poster = "mskYkcgAMCOKncFMfTWAHL5sUTo.jpg",
                            ReleaseYear = 2013,
                            Runtime = 115,
                            Title = "Insaisissable"
                        },
                        new
                        {
                            MovieId = 27,
                            Poster = "cB46TSg3kGjq2eVy5kVUhlpUa1H.jpg",
                            ReleaseYear = 2013,
                            Runtime = 143,
                            Title = "L'homme d'acier"
                        },
                        new
                        {
                            MovieId = 28,
                            Poster = "Nkgaj3X0W2jHQ1TzHEgWFpN3kJ.jpg",
                            ReleaseYear = 2014,
                            Runtime = 107,
                            Title = "Sans arrêt"
                        },
                        new
                        {
                            MovieId = 29,
                            Poster = "pn0bw4DDYVarCLBbWRg1DWUkZPX.jpg",
                            ReleaseYear = 2014,
                            Runtime = 97,
                            Title = "Predestination"
                        },
                        new
                        {
                            MovieId = 30,
                            Poster = "e2sct49Yw8EJsBWT3gdmAOpEY9Y.jpg",
                            ReleaseYear = 2014,
                            Runtime = 114,
                            Title = "Entre les tombes"
                        },
                        new
                        {
                            MovieId = 31,
                            Poster = "AfKm745YiKJ14yp4UfA4jowBIPi.jpg",
                            ReleaseYear = 2015,
                            Runtime = 105,
                            Title = "Focus"
                        },
                        new
                        {
                            MovieId = 32,
                            Poster = "wjVn1Qng8B3ySvfJr4ovuehI141.jpg",
                            ReleaseYear = 2015,
                            Runtime = 137,
                            Title = "Dangereux 7"
                        },
                        new
                        {
                            MovieId = 33,
                            Poster = "w7Q9BAqpbPHSeo6ZDYRpFGpGUxn.jpg",
                            ReleaseYear = 2016,
                            Runtime = 129,
                            Title = "Insaisissable 2"
                        },
                        new
                        {
                            MovieId = 34,
                            Poster = "cqvNVmn25vCmBcbwSfR1KlSOBBH.jpg",
                            ReleaseYear = 2016,
                            Runtime = 124,
                            Title = "Jason Bourne"
                        },
                        new
                        {
                            MovieId = 35,
                            Poster = "bCqD2c1nJJY6q65VGBfMItgVvGx.jpg",
                            ReleaseYear = 2016,
                            Runtime = 122,
                            Title = "Inferno"
                        },
                        new
                        {
                            MovieId = 36,
                            Poster = "aqwQPVosPSjfXRF6bO9Wg48ylAR.jpg",
                            ReleaseYear = 2017,
                            Runtime = 90,
                            Title = "iBoy"
                        },
                        new
                        {
                            MovieId = 37,
                            Poster = "77Z0g5fc1qWJ7SfHyeiHsMkYx5O.jpg",
                            ReleaseYear = 2017,
                            Runtime = 133,
                            Title = "Spider-man : Les retrouvailles"
                        },
                        new
                        {
                            MovieId = 38,
                            Poster = "2oc9wS0PjiBVCnAvYqmenCQdRLO.jpg",
                            ReleaseYear = 2017,
                            Runtime = 118,
                            Title = "Mon meilleur ennemi"
                        },
                        new
                        {
                            MovieId = 39,
                            Poster = "y1zgYmxkQDvi9Tev74PYbmer2Mv.jpg",
                            ReleaseYear = 2017,
                            Runtime = 119,
                            Title = "Jumanji : Bienvenue dans la jungle"
                        },
                        new
                        {
                            MovieId = 40,
                            Poster = "vVusHIRlyyFVS42XnqZso2wGKr.jpg",
                            ReleaseYear = 2018,
                            Runtime = 112,
                            Title = "Venom"
                        },
                        new
                        {
                            MovieId = 41,
                            Poster = "bSMSO9xupd4R4vwTPqigHn2quLN.jpg",
                            ReleaseYear = 2019,
                            Runtime = 97,
                            Title = "Meurtre et mystère"
                        },
                        new
                        {
                            MovieId = 42,
                            Poster = "zrNKUa5SBUwue39coJArNdDgQJM.jpg",
                            ReleaseYear = 2019,
                            Runtime = 129,
                            Title = "Spider-Man : Loin des siens"
                        },
                        new
                        {
                            MovieId = 43,
                            Poster = "kgajCPm5pdH2Sa3CTCyHuUmQvgT.jpg",
                            ReleaseYear = 2019,
                            Runtime = 137,
                            Title = "Rapides et dangereux présentent: Hobbs et Shaw"
                        },
                        new
                        {
                            MovieId = 44,
                            Poster = "hiHsAVw2M6j3JHUOPoqAR7X55iB.jpg",
                            ReleaseYear = 2019,
                            Runtime = 128,
                            Title = "Terminator : Sombre destin"
                        },
                        new
                        {
                            MovieId = 45,
                            Poster = "vwuNoe7sCWxZw7Feo3iIhym5rKM.jpg",
                            ReleaseYear = 2020,
                            Runtime = 99,
                            Title = "Sonic le hérisson"
                        },
                        new
                        {
                            MovieId = 46,
                            Poster = "fePczipv6ZzDO2uoww4vTAu2Sq3.jpg",
                            ReleaseYear = 2020,
                            Runtime = 110,
                            Title = "Spenser : la justice à tout prix"
                        },
                        new
                        {
                            MovieId = 47,
                            Poster = "fNXKcqfD252Kk52AJb6arCYCDlS.jpg",
                            ReleaseYear = 2020,
                            Runtime = 101,
                            Title = "L'Art du crime"
                        },
                        new
                        {
                            MovieId = 48,
                            Poster = "4xiq5NpooMCBFjQhGQjx8LqmhTy.jpg",
                            ReleaseYear = 2020,
                            Runtime = 93,
                            Title = "Scooby!"
                        },
                        new
                        {
                            MovieId = 49,
                            Poster = "pSGO3h6Cyqgv1bDbkjzxUlU8jsW.jpg",
                            ReleaseYear = 2020,
                            Runtime = 125,
                            Title = "The Old Guard"
                        },
                        new
                        {
                            MovieId = 50,
                            Poster = "k342BTraGregKSIVrrH7AGqoKna.jpg",
                            ReleaseYear = 2020,
                            Runtime = 103,
                            Title = "La nuit où on a sauvé Maman"
                        },
                        new
                        {
                            MovieId = 51,
                            Poster = "zDtraIGPVhmSnPZQ34fmyvWT5tz.jpg",
                            ReleaseYear = 2020,
                            Runtime = 123,
                            Title = "Enola Holmes"
                        },
                        new
                        {
                            MovieId = 52,
                            Poster = "gS1C3cIXJXHZbW00PtWy1bSdorH.jpg",
                            ReleaseYear = 2021,
                            Runtime = 102,
                            Title = "La femme à la fenêtre"
                        },
                        new
                        {
                            MovieId = 53,
                            Poster = "dFMu4ZfJf0tfgJkR0x3sRpeG0Rj.jpg",
                            ReleaseYear = 2021,
                            Runtime = 117,
                            Title = "La femme de mon meilleur ennemi"
                        },
                        new
                        {
                            MovieId = 54,
                            Poster = "iPTZGFmPs7HsXHYxiuxGolihjOH.jpg",
                            ReleaseYear = 2021,
                            Runtime = 127,
                            Title = "L'armée des voleurs"
                        },
                        new
                        {
                            MovieId = 55,
                            Poster = "5OCzQvJ0ePPx66OPGVC6ga9bUUQ.jpg",
                            ReleaseYear = 2022,
                            Runtime = 106,
                            Title = "Adam à travers le temps"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
